version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3007:3007"
    volumes:
      - .:/app
      - /app/node_modules  # Persist node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # Optional: for hot reloading
    env_file:
      - .env
    networks:
      - smart-feeds-network  # Thêm service vào mạng olh_news


networks:
  smart-feeds-network:
    driver: bridge